version: '3.8'
services:
  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=userdb  # ‚Üê Cambiado a userdb
    volumes:
      - mongodb_data:/data/db

  backend:
    build: ./backend/backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/userdb  
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
      - MONGODB_DATABASE=userdb
    depends_on:
      - mongodb
    volumes:
      - ./backend/backend:/app
      - ~/.m2:/root/.m2

  frontend:
    build: ./frontend/frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend/frontend:/app
      - /app/node_modules

volumes:
  mongodb_data: